version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: supersecret
    volumes:
      - /var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
        
  app:
    build: .
    env_file: .env
    volumes:
      - .:/opt/main/api
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
    ports:
      - "8080:8080"
